---
title: Software Carpentry @ MQ
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Website and blog for Software Carpentry events at Macquarie University,
  Australia.

'
baseurl: ''
url: MQ-software-carpentry.github.io
github_username: MQ-software-carpentry
markdown: kramdown
